/** Disco speech lines — shown in Dekko font during disco mode */
export const DISCO_LINES: string[] = [
  "This is my JAM!",
  "Resistance is futile on the dance floor!",
  "Starfleet Academy never taught me these moves!",
  "Somebody beam me to Studio 54!",
  "Engage... the dance floor!",
  "I'm giving it all she's got, Captain!",
  "Live long and BOOGIE!",
  "Set phasers to FUNKY!",
  "Boldly grooving where no one has grooved before!",
  "The final frontier... of dance!",
  "Warp factor DISCO!",
  "Captain's log: we are VIBING!",
  "This violates at least three regulations!",
  "I regret nothing!",
  "Shields down, moves UP!",
  "Red alert never sounded so good!",
  "Is this what shore leave feels like?",
  "The Romulans could never!",
  "Forget the Kobayashi Maru, this is the real test!",
  "My tricorder is detecting maximum groove!",
  "Even Vulcans would tap their feet!",
  "Permission to get down, sir!",
  "Permission granted... PERMANENTLY!",
  "HR will hear about this... later!",
  "The dilithium crystals are PUMPING!",
];
