import type { PunExchange } from "../types.js";

/**
 * 100 space puns for idle chatter when the captain is on the bridge.
 * Officers are assigned at runtime by the idle behavior manager.
 */
export const PUNS: PunExchange[] = [
  // --- Star Trek specific (~30) ---
  { setup: "Why did the Klingon cross the road?", punchline: "To conquer the other side!" },
  { setup: "How do Vulcans say goodbye?", punchline: "Live long and phosphor." },
  { setup: "What do you call a Tribble in a blender?", punchline: "Trouble." },
  { setup: "Why don't red shirts ever win at poker?", punchline: "They always fold early." },
  { setup: "What's a Borg's favorite band?", punchline: "The Assimilators." },
  { setup: "Why was the holodeck depressed?", punchline: "It had too many unresolved projections." },
  { setup: "What do you call a Romulan who tells jokes?", punchline: "A laugh-cloaker." },
  { setup: "Why is Worf bad at customer service?", punchline: "He only knows how to escalate." },
  { setup: "What did Picard say to the data entry clerk?", punchline: "Make it so... in the spreadsheet." },
  { setup: "Why don't Ferengi share their dessert?", punchline: "The 34th Rule of Acquisition: never give away the pudding." },
  { setup: "What's Scotty's favorite cocktail?", punchline: "Anything with more power." },
  { setup: "Why did Spock look up the dictionary?", punchline: "He found the definition of 'fun' fascinating." },
  { setup: "What do you call a lazy Klingon?", punchline: "Dishon-nap-able." },
  { setup: "Why is the Enterprise so clean?", punchline: "Because of the Dyson Sphere." },
  { setup: "What did the Borg say at the buffet?", punchline: "Resistance to seconds is futile." },
  { setup: "How does a Vulcan apologize?", punchline: "Logically." },
  { setup: "What's a Bajoran's favorite exercise?", punchline: "Resistance training." },
  { setup: "Why do Betazoids make terrible poker players?", punchline: "They always know your hand." },
  { setup: "What did Riker say about the new chairs?", punchline: "They really grow on you when you lean into them." },
  { setup: "Why was Geordi's date cancelled?", punchline: "He couldn't see it working out." },
  { setup: "What's Data's favorite meal?", punchline: "Microchips and dip." },
  { setup: "Why don't they play hide and seek on the Enterprise?", punchline: "Because the computer always finds you." },
  { setup: "What do you call a Cardassian art critic?", punchline: "A Gul-lery owner." },
  { setup: "How does Kirk pick his crew?", punchline: "He goes with his gut, and sometimes his shirt rips." },
  { setup: "Why did the photon torpedo fail the exam?", punchline: "It bombed." },
  { setup: "What's Q's least favorite game?", punchline: "Simon Says — he prefers Q Says." },
  { setup: "Why was the replicator in therapy?", punchline: "It had an identity crisis — tea or coffee?" },
  { setup: "What do you call a Trill with two jobs?", punchline: "A joint venture." },
  { setup: "Why did the Changeling go to acting school?", punchline: "It wanted to get into character." },
  { setup: "What's Wesley Crusher's WiFi password?", punchline: "ShutUpWesley2366." },

  // --- General space/science (~30) ---
  { setup: "Why did the sun go to school?", punchline: "To get a little brighter." },
  { setup: "How do you organize a space party?", punchline: "You planet." },
  { setup: "What kind of music do planets like?", punchline: "Neptunes." },
  { setup: "Why did the astronaut break up with his girlfriend?", punchline: "He needed more space." },
  { setup: "What do you call a tick on the moon?", punchline: "A luna-tick." },
  { setup: "How do you know when the moon has had enough to eat?", punchline: "When it's full." },
  { setup: "Why can't you trust atoms?", punchline: "They make up everything." },
  { setup: "What did Mars say to Saturn?", punchline: "Give me a ring sometime." },
  { setup: "Why did the black hole break up with the star?", punchline: "It was too clingy." },
  { setup: "What's a light year?", punchline: "Same as a regular year but with fewer calories." },
  { setup: "How does the solar system hold up its pants?", punchline: "With an asteroid belt." },
  { setup: "Why did Venus apply for a job?", punchline: "It wanted to be a star." },
  { setup: "What do planets use to download music?", punchline: "Neptunes." },
  { setup: "Why was the comet so popular?", punchline: "Because it was a trending star." },
  { setup: "How do astronomers get clean?", punchline: "They take a meteor shower." },
  { setup: "What's a spacecraft's favorite key?", punchline: "The space bar." },
  { setup: "Why did the neutron star start a podcast?", punchline: "It had a lot of spin." },
  { setup: "What did the alien say to the garden?", punchline: "Take me to your weeder." },
  { setup: "Why don't scientists trust stairs in space?", punchline: "They're always up to something." },
  { setup: "How does the man on the moon get his hair cut?", punchline: "Eclipse it." },
  { setup: "Why was the nebula so dramatic?", punchline: "It was always making a scene." },
  { setup: "What do you get when you cross a galaxy with a toad?", punchline: "Star Warts." },
  { setup: "Why was Pluto's party so small?", punchline: "It couldn't planet in time. Also, it got demoted." },
  { setup: "What's a supernova's favorite snack?", punchline: "Pop stars." },
  { setup: "Why did the rocket scientist fail at comedy?", punchline: "His delivery was too fast." },
  { setup: "What did the astronaut say when he bumped into the space station?", punchline: "Sorry, I didn't see you, you're too far out." },
  { setup: "Why do astronomers always carry notebooks?", punchline: "In case they see a star they want to jot down." },
  { setup: "How does a gravity scientist flirt?", punchline: "I'm attracted to you." },
  { setup: "Why is the dark side of the moon so lonely?", punchline: "No one ever visits." },
  { setup: "What did the telescope say to the star?", punchline: "I've got my eye on you." },

  // --- Ship/naval (~20) ---
  { setup: "Why are shields always so stressed?", punchline: "They're under constant pressure." },
  { setup: "What did the phaser say to the target?", punchline: "I'm stunning, aren't I?" },
  { setup: "Why was the transporter nervous?", punchline: "It was scattering." },
  { setup: "What's a deflector dish's life motto?", punchline: "Just keep bouncing back." },
  { setup: "Why was the warp core grumpy?", punchline: "Too much stress on the containment field." },
  { setup: "What do you call a ship that can't stop?", punchline: "An impulse buyer." },
  { setup: "Why did the torpedo go to therapy?", punchline: "It had explosive feelings." },
  { setup: "What did the hull say after the asteroid hit?", punchline: "That really dented my confidence." },
  { setup: "Why is the bridge the best place on the ship?", punchline: "Because that's where all the viewpoints are." },
  { setup: "What did Engineering say to the Bridge?", punchline: "Stop asking for more power, we're tapped out!" },
  { setup: "How does a starship get a date?", punchline: "It uses its tractor beam." },
  { setup: "Why was the airlock sad?", punchline: "Everyone kept leaving through it." },
  { setup: "What do you call a ship with a broken replicator?", punchline: "A fast." },
  { setup: "Why did the shuttle crash the party?", punchline: "It needed a docking permit." },
  { setup: "What's a turbolift's favorite saying?", punchline: "Things are looking up!" },
  { setup: "Why don't ships gossip?", punchline: "Because loose lips sink ships... wait." },
  { setup: "What did the nacelle say to the other nacelle?", punchline: "We make a great pair." },
  { setup: "Why is the ready room always calm?", punchline: "Because the captain keeps it in order." },
  { setup: "What's a photon torpedo's workout routine?", punchline: "Explosive reps." },
  { setup: "Why did the cloaking device fail the interview?", punchline: "It couldn't make itself visible." },

  // --- Office-in-space crossover (~20) ---
  { setup: "Why was the cosmic deadline so scary?", punchline: "It was approaching at warp speed." },
  { setup: "What does space coffee taste like?", punchline: "Out of this world, but the replicator still gets it wrong." },
  { setup: "How are space meetings different from regular ones?", punchline: "They're still boring, just with better views." },
  { setup: "Why did the IT admin go to the holodeck?", punchline: "To simulate a day without tickets." },
  { setup: "What did the sysadmin say about the starbase network?", punchline: "Have you tried turning the subspace relay off and on?" },
  { setup: "Why is filing reports in space worse?", punchline: "Because they have to be in triplicate across three quadrants." },
  { setup: "What's a Starfleet officer's worst nightmare?", punchline: "A performance review from a Vulcan." },
  { setup: "How do you fix a broken meeting in space?", punchline: "You add more stakeholders from different sectors." },
  { setup: "Why is the break room on deck 7 always empty?", punchline: "The replicator only makes Earl Grey." },
  { setup: "What did the ensign say about Monday mornings?", punchline: "Even in space, they still exist." },
  { setup: "Why are space spreadsheets the worst?", punchline: "They have infinite columns." },
  { setup: "What happened at the intergalactic team building event?", punchline: "Trust falls in zero gravity — nobody fell." },
  { setup: "Why did the officer bring a PADD to dinner?", punchline: "Can't stop working, the captain might call." },
  { setup: "What's the worst thing about a space standup meeting?", punchline: "In zero gravity, you're always standing up." },
  { setup: "How does the IT department fix a warp drive?", punchline: "Same as everything — restart it." },
  { setup: "Why did the budget meeting last 7 hours?", punchline: "Time dilation near the accountant's black hole of spreadsheets." },
  { setup: "What's on the agenda for today's staff meeting?", punchline: "The same thing as last week: everything is urgent." },
  { setup: "Why does HR send memos by subspace?", punchline: "So nobody can claim they didn't get them." },
  { setup: "What did FynBus say about the new shuttle route?", punchline: "Please ensure all passengers have a valid zone ticket, even in orbit." },
  { setup: "Why was the replicator's coffee budget cut?", punchline: "Accounting said synthesizing mocha lattes wasn't 'mission critical.'" },
];
